"""add file_url column recipe

Revision ID: 02d3b203bcb9
Revises: cef77d6c0046
Create Date: 2025-11-24 06:47:30.758339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d3b203bcb9'
down_revision: Union[str, Sequence[str], None] = 'cef77d6c0046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('file_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'file_url')
    # ### end Alembic commands ###
