"""adjust column activity

Revision ID: 1b054170c79d
Revises: 78f4b5b8283f
Create Date: 2025-11-12 02:35:01.474931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b054170c79d'
down_revision: Union[str, Sequence[str], None] = '78f4b5b8283f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_diary_analysis', sa.Column('activity', sa.String(), nullable=False))
    op.drop_column('user_nutritions', 'type_of_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_nutritions', sa.Column('type_of_activity', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('food_diary_analysis', 'activity')
    # ### end Alembic commands ###
