"""adjustment table exercise

Revision ID: 2936d0dcdd6a
Revises: 1b054170c79d
Create Date: 2025-11-12 08:03:31.964577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2936d0dcdd6a'
down_revision: Union[str, Sequence[str], None] = '1b054170c79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_habit_answers', sa.Column('selected_option', sa.String(length=50), nullable=True))
    op.add_column('exercise_habit_answers', sa.Column('answer_text', sa.String(), nullable=True))
    op.drop_column('exercise_habit_answers', 'reward_claimed')
    op.drop_column('exercise_habit_answers', 'frequency')
    op.add_column('exercise_habit_questions', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('exercise_habit_questions', sa.Column('question_type', sa.String(length=50), nullable=False))
    op.add_column('exercise_habit_questions', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_habit_questions', 'order')
    op.drop_column('exercise_habit_questions', 'question_type')
    op.drop_column('exercise_habit_questions', 'options')
    op.add_column('exercise_habit_answers', sa.Column('frequency', postgresql.ENUM('never', 'rarely', 'often', 'very_often', name='exercise_frequency_enum'), autoincrement=False, nullable=False))
    op.add_column('exercise_habit_answers', sa.Column('reward_claimed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('exercise_habit_answers', 'answer_text')
    op.drop_column('exercise_habit_answers', 'selected_option')
    # ### end Alembic commands ###
