"""add marchandise claim

Revision ID: 664279e671f9
Revises: aec828a05de9
Create Date: 2025-12-02 06:46:00.756651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664279e671f9'
down_revision: Union[str, Sequence[str], None] = 'aec828a05de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchandise_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('merchandise_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name='chk_claim_qty_positive'),
    sa.ForeignKeyConstraint(['merchandise_id'], ['merchandise.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchandise_claims_merchandise_id'), 'merchandise_claims', ['merchandise_id'], unique=False)
    op.create_index(op.f('ix_merchandise_claims_user_id'), 'merchandise_claims', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchandise_claims_user_id'), table_name='merchandise_claims')
    op.drop_index(op.f('ix_merchandise_claims_merchandise_id'), table_name='merchandise_claims')
    op.drop_table('merchandise_claims')
    # ### end Alembic commands ###
