"""add enum appointment_status_enum

Revision ID: 6cbcb0182479
Revises: 82f0a9e0b985
Create Date: 2025-12-27 10:44:25.134084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbcb0182479'
down_revision: Union[str, Sequence[str], None] = '82f0a9e0b985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_diary_items', 'weight_grams',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Total weight of food consumed in grams')
    op.execute("ALTER TYPE appointment_status_enum ADD VALUE 'rejected'")
    op.execute("ALTER TYPE appointment_status_enum ADD VALUE 'approved'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_diary_items', 'weight_grams',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Total weight of food consumed in grams')
    # ### end Alembic commands ###
