"""input bmi referencee data

Revision ID: 78f4b5b8283f
Revises: fdb961c226e2
Create Date: 2025-11-10 06:59:30.913543

"""
import uuid
import pandas as pd
import sqlalchemy as sa

from alembic import op
from pathlib import Path
from datetime import timezone, datetime
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '78f4b5b8283f'
down_revision: Union[str, Sequence[str], None] = 'fdb961c226e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    csv_path = Path("app/data/bmi_references.csv")
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    df = pd.read_csv(csv_path)
    now = datetime.now(timezone.utc)

    df.insert(0, "id", [str(uuid.uuid4()) for _ in range(len(df))])
    df["created_at"] = now
    df["updated_at"] = None
    df["deleted_at"] = None

    insert_stmt = sa.text("""
        INSERT INTO bmi_reference (
            id, gender, age_years, age_months,
            sd_minus_3, sd_minus_2, sd_minus_1,
            median, sd_plus_1, sd_plus_2, sd_plus_3,
            created_at, updated_at, deleted_at
        ) VALUES (
            :id, :gender, :age_years, :age_months,
            :sd_minus_3, :sd_minus_2, :sd_minus_1,
            :median, :sd_plus_1, :sd_plus_2, :sd_plus_3,
            :created_at, :updated_at, :deleted_at
        )
    """)

    conn.execute(sa.text("TRUNCATE TABLE bmi_reference RESTART IDENTITY CASCADE;"))
    conn.execute(insert_stmt, df.to_dict(orient="records"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM bmi_reference;"))
    # ### end Alembic commands ###
