"""add weight_grams

Revision ID: 82f0a9e0b985
Revises: d0c5becb0c78
Create Date: 2025-12-15 03:46:57.961994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f0a9e0b985'
down_revision: Union[str, Sequence[str], None] = 'd0c5becb0c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_diary_items', sa.Column('weight_grams', sa.Integer(), nullable=False, comment='Total weight of food consumed in grams'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_diary_items', 'weight_grams')
    # ### end Alembic commands ###
