"""refactor duration sleep to hour

Revision ID: aec828a05de9
Revises: c708b6d755b2
Create Date: 2025-12-01 07:22:48.420298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aec828a05de9'
down_revision: Union[str, Sequence[str], None] = 'c708b6d755b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep_records', sa.Column('target_sleep_hours', sa.Integer(), nullable=True))
    op.alter_column('sleep_records', 'sleep_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('sleep_records', 'wake_up_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('sleep_records', 'target_sleep_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep_records', sa.Column('target_sleep_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('sleep_records', 'wake_up_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('sleep_records', 'sleep_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('sleep_records', 'target_sleep_hours')
    # ### end Alembic commands ###
