"""add sleep table

Revision ID: bea543274892
Revises: 2936d0dcdd6a
Create Date: 2025-11-14 09:19:21.879669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea543274892'
down_revision: Union[str, Sequence[str], None] = '2936d0dcdd6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('wake_up_time', sa.Time(), nullable=False),
    sa.Column('sleep_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('target_sleep_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_records_user_id'), 'sleep_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_records_user_id'), table_name='sleep_records')
    op.drop_table('sleep_records')
    # ### end Alembic commands ###
