"""add category code enum

Revision ID: cef77d6c0046
Revises: 907337a01eb0
Create Date: 2025-11-24 03:08:03.394115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef77d6c0046'
down_revision: Union[str, Sequence[str], None] = '907337a01eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_VALUES = [
    "bodyweight_monitoring",
    "konseling_gizi",
    "konseling_psikolog",
    "forum_post",
    "chat_friend",
    "read_menu_sehat",
    "set_reminder",
]

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    for val in NEW_VALUES:
        conn.execute(
            sa.text(f"ALTER TYPE cat_code_enum ADD VALUE IF NOT EXISTS '{val}'")
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
