"""add rename name clumn games

Revision ID: d0c5becb0c78
Revises: 3e62b28a91e4
Create Date: 2025-12-04 08:55:34.865501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c5becb0c78'
down_revision: Union[str, Sequence[str], None] = '3e62b28a91e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('games', 'namename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('namename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('games', 'name')
    # ### end Alembic commands ###
