"""Add BMI Referencee

Revision ID: fdb961c226e2
Revises: 2195fb2c9d18
Create Date: 2025-11-10 04:54:33.834686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb961c226e2'
down_revision: Union[str, Sequence[str], None] = '2195fb2c9d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bmi_reference',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age_years', sa.Integer(), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('sd_minus_3', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('sd_minus_2', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('sd_minus_1', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('median', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('sd_plus_1', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('sd_plus_2', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('sd_plus_3', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gender', 'age_years', 'age_months', name='uq_gender_age')
    )
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    op.drop_table('bmi_reference')
    # ### end Alembic commands ###
